### ISSUE TITLE
Launcher refuses to download or place bin/client.dll and bin/server.dll

### ISSUE THREAD

**Issue by altro50** [int-72h/oflauncher-rei#11]
See title, I'm attempting to install under Windows. I have deleted my installation due to missing materials and then attempted to reinstall, now I'm missing client.dll, making it unbootable to begin with, argh! I'm not sure what to blame this on, but either way I am not getting any errors from the launcher's side.

I am definitely missing files, just see the listing of /bin:
HLLib.dll
fmod.dll
game_shader_dx9.so
libdiscord-rpc.so
discord-rpc.dll
game_shader_dx9.dll
gameui.dll
libfmod.so.11

**Comment by brysondev** [comment]
![image](https://user-images.githubusercontent.com/13501615/171662336-945315fb-0a12-414a-a07c-1d3d644a7eef.png)

**Comment by int-72h** [comment]
Try deleting your install completely or the .revision folder.

**Comment by brysondev** [comment]
> I've actually done this out of desperation already, I tried to do an install over the existing install, which did magically make some of the missing material files appear, but not client.dll.

That sounds like an antivirus issue then, since dlls always get flagged by windows. Just my 2 cents tho cuz we've tested this and had some hiccups but in the end we get all the files.

**Comment by altro50** [comment]
> That sounds like an antivirus issue then, since dlls always get flagged by windows

I would assume the IO functions would throw an exception in the case of an anti-virus intervening, in most languages the call would fail, I have however run it with defender disabled and the launcher elevated, same result

I've also attempted to install it outside of the sourcemods directory, just to see if it makes a difference, it doesn't.

But then, I had an absolute brain blast, I installed it to my C drive, instead of another drive (my sourcemods directory is a symlink to another drive), and it works. This could however, just be a coincidence and I can't seem to find a full file listing that would let me check for any other missing files.

Btw, a fun metric, when I copied it over to the broken install directory, it found 7176 files that already existed, vs the 18819 from the full(?) install, so over half of the files were missing.

**Comment by altro50** [comment]
I've given up on using the launcher, I wrote my own script to download the files using the revision files (and also made it check the hash, just in case the server returns bad data, such as html-based errors).. I hope it works fine in the future (And I have checked the launcher's code, I have no clue what's going on either!)
