### ISSUE TITLE
[QUESTION] Why do we write to a temp file in CLI?

### ISSUE THREAD

**Issue by AyeTSG** [int-72h/oflauncher-rei#8]
https://github.com/int-72h/oflauncher-rei/blob/cb7963086bb1b46d6299722b7bbdd4d1651200af/cli.py#L48

Just curious, why are we writing to a temp file when downloading from a toast repository? Wouldn't it be more efficient to just download to the end location instead?

**Comment by int-72h** [comment]
This is for atomicity- if your computer shuts town halfway through it isn't in a state between the revisions.
